version: '3.9'
services:
  app:
    container_name: health-zone-api
    build:
      context: .
      dockerfile: Dockerfile
    image: health-zone-api:1.0.0  
    restart: always
    ports:
      - 44398:8080